# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ga_pb2 as ga__pb2


class GeneticAlgorithmStub(object):
    """The Genetic Algorithm service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateLayout = channel.unary_unary(
                '/GeneticAlgorithm/GenerateLayout',
                request_serializer=ga__pb2.LayoutRequest.SerializeToString,
                response_deserializer=ga__pb2.LayoutReply.FromString,
                )


class GeneticAlgorithmServicer(object):
    """The Genetic Algorithm service.
    """

    def GenerateLayout(self, request, context):
        """Generates Layout
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneticAlgorithmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateLayout': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateLayout,
                    request_deserializer=ga__pb2.LayoutRequest.FromString,
                    response_serializer=ga__pb2.LayoutReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GeneticAlgorithm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GeneticAlgorithm(object):
    """The Genetic Algorithm service.
    """

    @staticmethod
    def GenerateLayout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GeneticAlgorithm/GenerateLayout',
            ga__pb2.LayoutRequest.SerializeToString,
            ga__pb2.LayoutReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
