# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ga.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ga.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08ga.proto\"\xa7\x01\n\rLayoutRequest\x12&\n\x07metrics\x18\x01 \x03(\x0e\x32\x15.LayoutRequest.Metric\"n\n\x06Metric\x12\x17\n\x13WEIGHT_OPTIMIZATION\x10\x00\x12\x1b\n\x17TIME_SPACE_OPTIMIZATION\x10\x01\x12\x13\n\x0fMINIMIZE_ERRORS\x10\x02\x12\x19\n\x15HARDWARE_OPTIMIZATION\x10\x03\"\x1e\n\x0bLayoutReply\x12\x0f\n\x07layouts\x18\x01 \x01(\t2D\n\x10GeneticAlgorithm\x12\x30\n\x0eGenerateLayout\x12\x0e.LayoutRequest\x1a\x0c.LayoutReply\"\x00\x62\x06proto3'
)



_LAYOUTREQUEST_METRIC = _descriptor.EnumDescriptor(
  name='Metric',
  full_name='LayoutRequest.Metric',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WEIGHT_OPTIMIZATION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TIME_SPACE_OPTIMIZATION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MINIMIZE_ERRORS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HARDWARE_OPTIMIZATION', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=70,
  serialized_end=180,
)
_sym_db.RegisterEnumDescriptor(_LAYOUTREQUEST_METRIC)


_LAYOUTREQUEST = _descriptor.Descriptor(
  name='LayoutRequest',
  full_name='LayoutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='LayoutRequest.metrics', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LAYOUTREQUEST_METRIC,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=180,
)


_LAYOUTREPLY = _descriptor.Descriptor(
  name='LayoutReply',
  full_name='LayoutReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='layouts', full_name='LayoutReply.layouts', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=212,
)

_LAYOUTREQUEST.fields_by_name['metrics'].enum_type = _LAYOUTREQUEST_METRIC
_LAYOUTREQUEST_METRIC.containing_type = _LAYOUTREQUEST
DESCRIPTOR.message_types_by_name['LayoutRequest'] = _LAYOUTREQUEST
DESCRIPTOR.message_types_by_name['LayoutReply'] = _LAYOUTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LayoutRequest = _reflection.GeneratedProtocolMessageType('LayoutRequest', (_message.Message,), {
  'DESCRIPTOR' : _LAYOUTREQUEST,
  '__module__' : 'ga_pb2'
  # @@protoc_insertion_point(class_scope:LayoutRequest)
  })
_sym_db.RegisterMessage(LayoutRequest)

LayoutReply = _reflection.GeneratedProtocolMessageType('LayoutReply', (_message.Message,), {
  'DESCRIPTOR' : _LAYOUTREPLY,
  '__module__' : 'ga_pb2'
  # @@protoc_insertion_point(class_scope:LayoutReply)
  })
_sym_db.RegisterMessage(LayoutReply)



_GENETICALGORITHM = _descriptor.ServiceDescriptor(
  name='GeneticAlgorithm',
  full_name='GeneticAlgorithm',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=214,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateLayout',
    full_name='GeneticAlgorithm.GenerateLayout',
    index=0,
    containing_service=None,
    input_type=_LAYOUTREQUEST,
    output_type=_LAYOUTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENETICALGORITHM)

DESCRIPTOR.services_by_name['GeneticAlgorithm'] = _GENETICALGORITHM

# @@protoc_insertion_point(module_scope)
