insert into Cars (id, name) values (1, 'E-Class');
insert into Cars (id, name) values (2, 'Mazdaspeed 3');
insert into Cars (id, name) values (3, 'Millenia');
insert into Cars (id, name) values (4, 'C-Class');
insert into Cars (id, name) values (5, 'Century');
insert into Cars (id, name) values (6, 'SL-Class');
insert into Cars (id, name) values (7, 'X5');
insert into Cars (id, name) values (8, '626');
insert into Cars (id, name) values (9, 'Sunfire');
insert into Cars (id, name) values (10, 'Celica');
insert into Cars (id, name) values (11, 'Elan');
insert into Cars (id, name) values (12, 'Cirrus');
insert into Cars (id, name) values (13, 'HHR');
insert into Cars (id, name) values (14, 'Mustang');
insert into Cars (id, name) values (15, 'CX-9');
insert into Cars (id, name) values (16, 'IS');
insert into Cars (id, name) values (17, 'MX-5');
insert into Cars (id, name) values (18, 'Taurus');
insert into Cars (id, name) values (19, '2500');
insert into Cars (id, name) values (20, 'Ram 3500');